[package]
name = "tui-tree-widget"
description = "Tree Widget for tui-rs"
version = "0.12.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/tui-rs-tree-widget"
authors = ["EdJoPaTo <tui-tree-widget-rust-crate@edjopato.de>"]
edition = "2021"
rust-version = "1.56.1"
keywords = ["tui", "terminal", "tree", "widget"]
categories = ["command-line-interface"]
include = ["src/**/*", "README.md"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { git = "https://github.com/uberFoo/ratatui", default-features = false }

unicode-width = "0.1"

[dev-dependencies]
crossterm = "0.25"
tui = "0.19"
